language: python
python:
- '3.6'
- pip
before_install:
- openssl aes-256-cbc -K $encrypted_2ede7b5765d2_key -iv $encrypted_2ede7b5765d2_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
install:
- pip install -U setuptools
- pip install ansible==2.4 molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: vxtMtU9Vt2CdruuV0gEK8EVF4sk7wQPJt6/k7p9Z98rFsB/+x4BdWQtH/LcA9b++rIFi2fT9IF87KH11huwTcNenY9WH40RKYqq+z4lzpPnHSVroUy36RRwXjhXo6oefDpA5sMFlJw9AuL131otGhukbPUDwqL/sSKt7cbIzRj+BlBTZr8UO23yCpMiKm3xbun4VMfNOwLRlxCijx4rfP+iSF8QEokbPVJiZ1ULrjhfrlAPnKX6FwEN02HUM4Aag1fOtwclQr+JE+a/FitDt9QMc/6V2JQZbc27blx1/S2AWAwC5/ZqQHpgogzqATVCi55yyommB6oiW8Xiyt3M/V5J8J0tCXStvb4eV4TDM8bMPAJligPLSXTasful+mmGpLpskDikUKXOYxeZG/9JGCIyEWmWq1ISevo3RM3Sc1DdevNI9IMAJh/C72h099KHcXHKPjBTAN6CaVb4WuQ4zSsX8VnVEqp79Hn5qYPdlyWcbtk9jBFQfILhEMXYai7zbYCQihz/rGZggirKbE5MCPSf6Ofr16HgzTwQEmhrWBVoXiAklYJQFa/T/Cn7Y5Tad4cJ6hvCss9ZKRwYA6sATUteale6r1eDsCu9me1qvML2YPIeokIZ/vJD2QCy0PiO4R1kKufl8dliyoIDPHFyHox9nJ3E53JFUXEDDyonKEpI=
  - secure: xk1FKlPjG7+7nP3gCuVLsG17iILHkn/LMoZvnCnw0p4IiSn0DM2rrK1IdfLDRoQ6WlipS0qFuIYcs4V6JZi6kpe8LGdUdjzrlVyH2lQX0BAEMtVuPWPJB1QhSOjTuYir6nqStKf5x3Qgt4XGrMHF32QDeZzl06MIUkGZTn8qh+qAJ43mao5igEqimxtdPLzLNrO4hdY/jE03HP6UjCFhBYSVbbMmwyAWnS3QycegYm+NvJ5OxA+oXvrIYwUyusQ8K85uvM4b2DeglxeCqP+Y9CBziXq6pU33OEsQAX6vY0BTp9u89vQ437vl/18lFZQqSeLNVFWmVZXLl/1oBCH6xwSRJSkUnkztWkj8gg68nQJv1VTeJOY00zKKK3CS125lZkC9zMEZJKPmZJkr/8qWmip5v3xOqJtPyqn+x0o7Gmx/KsX9QgJXwiqkHdvHYsnqOXQuiHOeG5PmFqWA524uqm/541S0uUSlaOgdcrZOcw0cw9qWlagYTZ+Hd6HPXtnGsIAdmo4wXwhq8qCthkFKi3Cj7f7BbG/mc7Hm4GPskCWzla2hDZiU4Zqb4SVWtkh3zbv2BTEKXX2keFlNWOYan/IrSY8QsZTITumw7n7JmpGemO17c6BjOY48N8vsOTkaasl6W1DtXQxRsm32kLTM8Ciq8T/qluCgM4o/5waTVSM=
  - secure: lStv9oTO4gI94fX44p4EFY/wWQp3JLci780+KS9v4x7TAZfFLkgf6uRXr+n/6s3LI67x5NoMMDZMyo/FPxzWZTUiKjjxFGlQpU90gFMIGma/mDylzPIaLFP6hb5MfaEpUlLp6EqJDA9xaCniVBoHPddOvYBjDYx8Koox69xy1sg4AWiJ5BvOdc1a6pueyvAe6S9gk0l+V6TiCbzJnHZ2ykdRfzL3NADoQikUWir8UeXuXjLUxYd080Y6m4iutRLKyHpQQRJO+EpUTJCyf94qlEq+urhYMn9MADoGsO529J0pO3rJGqnSyFno9dNPws8Dl4E32LR0AmoUe99JFNahZPCPtI30hCPKV33YCJ2UP8zC8emiZhWb4gauGnzooCPqk9/bENsEN05wSU4orIc9Bd2epseUq5aqd+voBSxXpWwGiV86WuNvqAwfk3eI60aHOO7OL/EdXp6m4pF5/3i6eLT5AnZoBpO5U1GvPIezQ38UXs9MHLGZ3zCTw0p5owF0Ah/FPj+KevOShfO/Q6LtYV9QtFmAIewNksltS0PaJjc/PNghIZDepAzWphhD2yv7lINt4I+LrLWuN9WXsDEFLz+sTtYJ4cAl8SI9UMYUGbS5ipOHBfeTsur8LMLjryCP5RdeZjpqNfFAnkzyt2V4S3da64ZLGPkxUY9ipUdIvb8=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy